### ISSUE TITLE
Cache error

### ISSUE THREAD

**Issue by jeff-hykin** [jordanreger/crate#1]
tried running the readme example, but sadly stuck on this error
<img width="718" alt="Screen Shot 2022-02-10 at 8 51 34 AM" src="https://user-images.githubusercontent.com/17692058/153432897-1bd0e01a-7862-49b8-9416-3d0317c5c728.png">

```
➜ deno --version                  
deno 1.17.1 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

Any guesses?

**Comment by jordanreger** [comment]
@jeff-hykin it's due to macOS — apparently i forgot to run deno_bindgen for mac and linux. i'll make sure i add support for it here soon!

**Comment by jordanreger** [comment]
i'm going to close this issue until progress on "pallet" (the part of the crate project that deals with native applications) is started back up again. currently it's just a web-based framework, but eventually i'll work my way back down and pallet will return.
